### ISSUE TITLE
Feedback from Konrad2

### ISSUE THREAD

**Issue by knyghtmare** [knyghtmare/Electrifyre#37]
S1
~They seem to approaching -> They seem to be approaching~
~The Fire Guardians are recruited with 25/30 hp~
`--------------------------------------------------------------------`
S2
~used to listed -> used to listen~
~The intro doesn't really make it clear the the 'modern hero' is talking about the founder of our protags village~
~My allies don't need any rescueing on hard. D:~

~Why does the Faerie say that she won'T be helping us, if she sticks around to attack my enemies?~
~Also, my allies guards went on the attack on turn 1.~
~Whoa~
~I find someone nearly dead~
~And I'm saying 'you can help us after you have healed up' xD~
~I think 'we can talk after you'Ve healed up' makes more sense~
`--------------------------------------------------------------------`

**Comment by Konrad22** [comment]
To organize it properly, and so that I can update it later:

###S1
~They seem to approaching -> They seem to be approaching~

~Fire Guardians are recruited with 25/30 hp, very very likely due to the 'resiliant' trait. Maybe it's being applied after they have been recruited? Basically a 25/25 unit is recruited, and then resiliant gets slapped on it -> suddenly 5 more max hp, but the amount of hp is left as 25.~

###S2
~used to listed -> used to listen~
~I cannot let you go on without giving nothing back -> I cannot let you go on without giving _anything_ back~

~It doesn't make much sense that the allied leader seems to be giving nothing, while my leader thanks her anyways.~

~The intro doesn't really make it clear the the 'modern hero' is talking about the founder of our protags village. 'Modern hero' does not make me think of someone who founded a village ages ago. Due to this it's also unclear if there was a Dunefolk/Aragwaith war going on recently, a parallel to the ancient times, or if it's just about an ancient Dunefolk/Aragwaith war. There is no clear distinction between 'back then' and 'now', making it appear as if that ancient hero fought in the war while our protag was training in the city of Aeranas.~

~My allies _only sometimes_ need any rescuing on hard.~
[Electrifyre-Wild Knolls-Auto-Save9.gz](https://github.com/user-attachments/files/16732177/Electrifyre-Wild.Knolls-Auto-Save9.gz)
[Electrifyre-Wild Knolls-Auto-Save5.gz](https://github.com/user-attachments/files/16734370/Electrifyre-Wild.Knolls-Auto-Save5.gz)
~My allies guards went on the attack on turn 1. Whether my allies need rescuing seems to depend on how unlucky the guards are after yoloing into the ants.~
![grafik](https://github.com/user-attachments/assets/4ad46b67-a01c-41aa-bc0a-a8b189cffb3d)

~The Faerie say that she won't be helping us, but sticks around to attack my enemies, as an unit of my allies. It feels odd that nothing happens when she dies.~

~Suggestion for that Strongbow we find:~
~Change 'you can help us after you have healed up' to something like 'we can talk after you've healed up'. The words of the Strongbow didn't seem to imply a desire to help **now**, it was just a thank you.
'you can help us after you have healed up' makes me think that the Strongbow doesn't get a choice in this, regardless of whether they've got the time or desire to help me in my quest. Very odd for a loyal unit. I also think it would make more sense for the rescued unit to be knocked out for the duration of the scenario. They do not 'sound' like they'd be able to instantly fight, which the played might very well force them to. :D~


### S3
~up.Turn -> up. Turn~
~They had passed -> They've passed~
~You are aragwaithi -> You are Aragwaithi~

**Comment by knyghtmare** [comment]
I have completed the issues pointed it in this ticket. If you have more feedback, then make a new ticket or post them in the Electrifyre feedback topic in WMG server/Wesnoth Forums.
